baseURL = "https://hidden-japan.tokyo/"
title = "Hidden Japan Tokyo"
theme = "PaperMod"
defaultContentLanguage = "en"

[languages]
  [languages.en]
    languageName = "English"
    weight = 1
    contentDir = "content/en"
  [languages.ko]
    languageName = "한국어"
    weight = 2
    contentDir = "content/ko"
  [languages.zh-tw]
    languageName = "繁體中文"
    weight = 3
    contentDir = "content/zh-tw"

[params]
  ShowReadingTime = true
  ShowShareButtons = true
  googleSiteVerification = "google63ababe7928e6cec.html"

[params.homeInfoParams]
  Title = "Discover Hidden Japan"
  Content = "Off-the-beaten-path travel guides for real explorers"


[menu]
  [[menu.main]]
    name = "By Region"
    url = "/tags/region/"
    weight = 1
  [[menu.main]]
    name = "By Theme"
    url = "/tags/theme/"
    weight = 2